apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbshop
  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://github.com/santosh662/Qualibytes-Ecommerce-v2.git

    targetRevision: dev

    path: kubernetes

  destination:

    server: https://kubernetes.default.svc

    namespace: qbshop

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

    - CreateNamespace=true
