apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbshop-ingress
  namespace: qbshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - qbshop.ishwarrugs.shop
    - ishwarrugs.shop
    secretName: qbshop-tls
  rules:
  - host: qbshop.ishwarrugs.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbshop-service
            port:
              number: 80
  - host: ishwarrugs.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbshop-service
            port:
              number: 80
