apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbshop-ingress
  namespace: qbshop
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx

  rules:
    - host: qbshop.ishwarrugs.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbshop-service
                port:
                  number: 80

    - host: ishwarrugs.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbshop-service
                port:
                  number: 80
